### PR TITLE
Add post Grabbing Growth: A Growth Hacking Story

### PR DESCRIPTION
**Pull request by paradite**
screen shot 2017-12-08 at 1 04 40 pm

### CODE REVIEW

**Comment by yangshun** [comment]
Resize the thumbnails for Huan Yang and Jiaying. They're currently 200kb each which is a lot for scaled down thumbnails.

**Comment by lowjoel** [comment]
Yeah, they should be resized first.

Side note: I'd imagine that resizing can be accomplished by a thumbnail generator plugin. I can't find one offhand, though.

**Comment by paradite** [comment]
okay will resize them

**Comment by paradite** [comment]
@yangshun @lowjoel resized. i think i will (or find someone to) find a plugin or write a script to do this next time.

**Pull request merged**
